### ISSUE TITLE
Crash upon using JEI to preview Tetra Items

### ISSUE THREAD

**Issue by Trilli** [LegoMaster3650/ItemUpgrader#5] opened 2023-02-09 06:08 UTC
Not sure which mod is causing it, but I thought I would open an issue if it is an easy fix somehow, I don't expect every mod to be compatible however. To recreate this, install tetra and its dependencies, same for ItemUpgrader, and JEI, then press the "Show recipes used in" key for JEI. The actual upgrading function already works and items can be put onto a tetra tool with no problems, besides when converting a normal tool to a tetra one, it loses the upgrade, but that was expected.

[crash-2023-02-09_00.56.58-client.txt](https://github.com/LegoMaster3650/ItemUpgrader/files/10693999/crash-2023-02-09_00.56.58-client.txt)

**Comment by LegoMaster3650** [comment] 2023-02-09 18:01
Alright looked into it a bit and it seems the bug here is the items have their ItemUpgrade tag applied, and it seems tetra has a failsafe for items with no nbt but not for items with nbt but no tetra tags. This seems to be an issue on tetra's side, although I may add a special case to my mod for this anyways.

**Comment by LegoMaster3650** [comment] 2023-02-27 23:40
Appears to have been fixed recently in tetra version 5.0.2, this issue will be closed soon as long as my testing doesn't prove otherwise.

**Comment by LegoMaster3650** [comment] 2023-03-02 17:45
Just tested it, confirmed this is fixed in tetra.

**Closed as completed by LegoMaster3650** 2023-03-02 17:45 UTC
Labels: bug
